### ISSUE TITLE
Comparing dollars and cents?

### ISSUE THREAD

**Issue by mhluska** [Sailias/bitcoin_payable#25] opened 2017-12-13 07:36 UTC
In payment_processor.rb we have this line: `if payment.currency_amount_paid >= payment.price`

It seems to me that `payment.currency_amount_paid` is a dollar value and `payment.price` is a cents value. Am I missing something?

Also, it seems that `btc_conversion` is a float but we store it as an integer according to the schema. Did this gem ever really work?

**Comment by Sailias** [comment] 2017-12-13 13:03
@mhluska the `currency_amount_paid` is a float rounded to 0 decimal places to compare with the integer.

`btc_conversion` is also an integer as it comes in as dollars and I convert to cents.

Can you outline what issues you're having?

**Comment by Sailias** [comment] 2017-12-13 13:05
Are you just getting floating point comparison errors which is the reason for your proposed fix of:

`if payment.currency_amount_paid >= payment.price / 100.0`

**Comment by mhluska** [comment] 2017-12-13 13:48
@Sailias the main reason for the `/ 100` is that in my code, `payment.currency_amount_paid` is 100x smaller than `payment.price`. For example, on my site I am trying to make a bitcoin purchase valued at 5 USD or 500 cents. After the payment is sent and confirmed, I end up with `5` for `payment.currency_amount_paid` and `500` for `payment.price` which seems to me like one is dollars and one is cents.

**Comment by Sailias** [comment] 2017-12-13 14:00
@mhluska that is certainly the cause of your issue. We multiply it by 100 because the price would come in as dollars and I convert it to cents. 

123.45 => 12345

This plus the .round(0) would result in proper comparisons.

**Comment by Sailias** [comment] 2017-12-13 14:01
I always like to work with cents when it comes to money to avoid floating point math errors.

**Comment by mhluska** [comment] 2017-12-13 14:08
Gotcha. I totally agree with working in cents. I was just confused why the `* 100` has to happen in the `get_btc` call. I agree that the conversion to cents has to happen at some point though.

**Comment by Sailias** [comment] 2017-12-13 15:07
@mhluska I'll have to check how your new price processor works and you receive it. 
If it comes in as a float, it should be converted to cents on ingestion as the db column is an integer.

I will close this issue and we can address this in your pull request.

**Closed by Sailias** 2017-12-13 15:07 UTC
